attempting to fix error in layout checker
ERROR: LoadError: StringIndexError: invalid index [21], valid nearby indices [20]=>'°', [22]=>'''
Stacktrace:
  [1] string_index_err(s::Token, i::Int64)
    @ Base ./strings/string.jl:12
  [2] SubString{Token}(s::Token, i::Int64, j::Int64)
    @ Base ./strings/substring.jl:32
  [3] SubString
    @ ./strings/substring.jl:38 [inlined]
  [4] SubString
    @ ./strings/substring.jl:40 [inlined]
  [5] getindex
    @ ./strings/substring.jl:255 [inlined]
  [6] check_delimiter(value::Tree)
    @ Main ~/work/cif_core/cif_core/julia_cif_tools/layout.jl:514
  [7] transformer_func(l::Linter, #unused#::Val{:scalar_item}, meta::Lerche.Meta, tree::Tree)
    @ Main ~/work/cif_core/cif_core/julia_cif_tools/layout.jl:491
  [8] _call_userfunc(v::Linter, tree::Tree)
    @ Lerche ~/.julia/packages/Lerche/QxD5R/src/visitors.jl:269
  [9] visit(v::Linter, tree::Tree)
    @ Lerche ~/.julia/packages/Lerche/QxD5R/src/visitors.jl:299
 [10] visit(v::Linter, tree::Tree) (repeats 5 times)
    @ Lerche ~/.julia/packages/Lerche/QxD5R/src/visitors.jl:296
 [11] lint_report(filename::String; ref_dic::String, import_dir::String, warn::Bool, no_text::Bool)
    @ Main ~/work/cif_core/cif_core/julia_cif_tools/linter.jl:50
 [12] top-level scope
    @ ~/work/cif_core/cif_core/julia_cif_tools/linter.jl:107
in expression starting at /home/runner/work/cif_core/cif_core/julia_cif_tools/linter.jl:104
Error: Process completed with exit code 1.